### ISSUE TITLE
Registering Pro3EM DB1 fails when wifi disabled with 'Error while extracting response...'

### ISSUE THREAD

**Issue by danpoltawski** [easimon/shelly-exporter#81]
Is there a way I can do some debugging to work out whats going on here?

```
2024-02-01T17:45:03.528Z  INFO 1 --- [   scheduling-1] c.d.s.e.d.ShellyGen2DeviceRegistry       : Added 1, removed 0, current amount: 1 devices.
2024-02-01T17:45:03.537Z  INFO 1 --- [   scheduling-1] c.d.s.e.metrics.ShellyGen2Metrics        : Registering ShellyDevice(mac=<redacted>, address=<redacted>, name=Pro3EM DB1, type=SPEM-003CEBEU, firmwareVersion=20231219-134001/1.1.0-g34b5d4f).
2024-02-01T17:45:03.909Z  WARN 1 --- [   scheduling-1] c.d.s.exporter.client.ShellyGen2Client   : GET http://10.10.16.44/rpc/Shelly.GetStatus: HTTP Request failure: Error while extracting response for type [class click.dobel.shelly.exporter.client.api.gen2.Gen2ShellyStatus] and content type [application/json]
```

Running on the latest docker image with `SHELLY_GEN2DEVICES_HOSTS` and `SHELLY_AUTH_PASSWORD` set

**Comment by easimon** [comment]
I think by setting the env vars `DEBUG=true` and/or `LOGGER_LEVEL_ROOT=debug` the log should display more details -- maybe even the raw request/response.

It seems like your Shelly responds with an unexpected json structure. No idea why, though. I have a Shelly 3EM pro as well, and the preliminary 2nd gen device support has been implemented specifically for this device.

**Comment by easimon** [comment]
Just tested it here.`LOGGING_LEVEL_ORG_APACHE_HC=debug` shows the response (and lots of other details), look for something like this:

```
2024-02-04T12:47:05.329+01:00 DEBUG 8288 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-8 << "{"ble":{}, "cloud":{"connected":true} ...
```

The interesting part would be the JSON body. I think there's some configuration difference between your and my 3EM Pro, that leads to a JSON response that is incompatible with the exporter client. Please tell me what it looks like. 

CAVEAT: 
- on debug log level, the HTTP client also logs authentication data. Make sure you redact these.
- the response body might contain data you would not want to expose, like your device's mac and ip address, wifi name etc.

I also added a fix to not swallow the Exception stack trace. Please retry with version 2.5.2 (should be available in a few minutes). Your error should also contain that stack trace then, something along

```
Cannot construct instance of `click.dobel.shelly.exporter.client.api.gen2.Gen2ShellyStatus`, problem: ...
```

The problem description should also give a hint on the JSON property that's either incompatible or even missing.

**Comment by danpoltawski** [comment]
Ahha  we have disabled wifi:
> Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `click.dobel.shelly.exporter.client.api.gen2.WifiStatus`,

Entire json response is:
```
{
  "ble": {},
  "cloud": {
    "connected": false
  },
  "em1:0": {
    "id": 0,
    "current": 0.029,
    "voltage": 0,
    "act_power": 0,
    "aprt_power": 0,
    "pf": 0,
    "freq": 0,
    "calibration": "factory"
  },
  "em1:1": {
    "id": 1,
    "current": 0.027,
    "voltage": 0,
    "act_power": 0,
    "aprt_power": 0,
    "pf": 0,
    "freq": 0,
    "calibration": "factory"
  },
  "em1:2": {
    "id": 2,
    "current": 25.426,
    "voltage": 239.3,
    "act_power": 1543.1,
    "aprt_power": 6072.3,
    "pf": 0.57,
    "freq": 49.9,
    "calibration": "factory"
  },
  "em1data:0": {
    "id": 0,
    "total_act_energy": 0.01,
    "total_act_ret_energy": 0
  },
  "em1data:1": {
    "id": 1,
    "total_act_energy": 0.01,
    "total_act_ret_energy": 0
  },
  "em1data:2": {
    "id": 2,
    "total_act_energy": 73247.3,
    "total_act_ret_energy": 0
  },
  "eth": {
    "ip": "10.10.16.44"
  },
  "modbus": {},
  "mqtt": {
    "connected": false
  },
  "sys": {
    "mac": "34987A686808",
    "restart_required": false,
    "time": "08:46",
    "unixtime": 1707209187,
    "uptime": 399674,
    "ram_size": 241672,
    "ram_free": 130660,
    "fs_size": 524288,
    "fs_free": 184320,
    "cfg_rev": 22,
    "kvs_rev": 0,
    "schedule_rev": 3,
    "webhook_rev": 3,
    "available_updates": {
      "beta": {
        "version": "1.2.0-beta1"
      }
    },
    "reset_reason": 3
  },
  "temperature:0": {
    "id": 0,
    "tC": 33.5,
    "tF": 92.2
  },
  "wifi": {
    "sta_ip": null,
    "status": "disconnected",
    "ssid": null,
    "rssi": 0
  },
  "ws": {
    "connected": false
  }
}
```

I can provide the whole debug log, but was just searching to avoid I don't accidentally share secrets

**Comment by easimon** [comment]
Okay I will have to make that optional then. Not sure when I have the time, but you are not forgotten!

**Comment by easimon** [comment]
Should be fixed with 2.5.5, please test it. Feel free to reopen when it does not fix your issue.

**Comment by danpoltawski** [comment]
Thanks for looking at this, there appears to be new error (json output similar to above)
```
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `click.dobel.shelly.exporter.client.api.gen2.Gen2ShellyStatus`, problem: Parameter specified as non-null is null: method click.dobel.shelly.exporter.client.api.gen2.Gen2ShellyStatus.<init>, parameter emStatus
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406) ~[spring-web-6.1.3.jar!/:6.1.3]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.1.3.jar!/:6.1.3]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103) ~[spring-web-6.1.3.jar!/:6.1.3]
```

**Comment by easimon** [comment]
This is interesting -- taking a closer look, this looks quite different from the response I get on my Shelly.

The field that fails is `em:0`, which contains the momentary power, voltage etc. for  all phases (named a, b, c) on my device... 

This is not there on your device... instead you have `em1:0` - `em1:2`... Same for `emdata:0` vs. `em1data:0`-`em1data:2`, most probably containing data sets for a single phase each.

The device type is the same as mine (from your first issue comment): "SPEM-003CEBEU", so this is supposed to be the same device. 

A small difference: the firmware version. 20231219-134001/1.1.0-g34b5d4f is yours, 20240213-140630/1.2.0-gb1b9aa8 is mine. Your device sees an available firmware update to "1.2.0-beta1", mine does not. I have not installed a beta firmware (I think). I have this device since July 2023, so at some point I assume I had your firmware version (and/or older ones) as well. 

For me, the JSON structure was "always" (at least since 07/2023) like this.

PS: you might want to remove the device MAC from the response above. 

```json
{
    "ble": {},
    "cloud": {
        "connected": true
    },
    "em:0": {
        "id": 0,
        "a_current": 0.419,
        "a_voltage": 236.6,
        "a_act_power": 92.6,
        "a_aprt_power": 99.1,
        "a_pf": 0.93,
        "a_freq": 50,
        "b_current": 0.081,
        "b_voltage": 237.5,
        "b_act_power": 5.6,
        "b_aprt_power": 19.2,
        "b_pf": 0.59,
        "b_freq": 50,
        "c_current": 0.397,
        "c_voltage": 236.8,
        "c_act_power": 67.5,
        "c_aprt_power": 93.8,
        "c_pf": 0.76,
        "c_freq": 50,
        "n_current": null,
        "total_current": 0.897,
        "total_act_power": 165.753,
        "total_aprt_power": 212.066,
        "user_calibrated_phase": []
    },
    "emdata:0": {
        "id": 0,
        "a_total_act_energy": 508572.13,
        "a_total_act_ret_energy": 0,
        "b_total_act_energy": 393113.22,
        "b_total_act_ret_energy": 0,
        "c_total_act_energy": 733431.03,
        "c_total_act_ret_energy": 0,
        "total_act": 1635116.38,
        "total_act_ret": 0
    },
    "eth": {
        "ip": null
    },
    "modbus": {},
    "mqtt": {
        "connected": false
    },
    "sys": {
        "mac": "REDACTED",
        "restart_required": false,
        "time": "09:07",
        "unixtime": 1708243650,
        "uptime": 122667,
        "ram_size": 240540,
        "ram_free": 115500,
        "fs_size": 524288,
        "fs_free": 192512,
        "cfg_rev": 21,
        "kvs_rev": 0,
        "schedule_rev": 0,
        "webhook_rev": 0,
        "available_updates": {},
        "reset_reason": 3
    },
    "temperature:0": {
        "id": 0,
        "tC": 30.4,
        "tF": 86.6
    },
    "wifi": {
        "sta_ip": "REDACTED",
        "status": "got ip",
        "ssid": "REDACTED",
        "rssi": -41
    },
    "ws": {
        "connected": false
    }
}
```

**Comment by easimon** [comment]
I have not yet understood the actual difference, but according to https://shelly-api-docs.shelly.cloud/gen2/Devices/Gen2/ShellyPro3EM/
The EM can operate in two "profiles", Monophase and Triphase.

Mine is set to "Triphase" and I assume yours is set to "Monophase". I think for German households like mine, Triphase is correct, but I don't know what exactly is changing when using Monophase. 

Not sure how/if I can cover both profiles in the exporter easily. Can you change yours to Triphase? I can be changed in the Shelly App.

**Comment by easimon** [comment]
One difference between Monophase and Triphase is, that you get a (netted) total across the three phases in Triphase mode. 

The netting makes a difference when you have e.g. solar panels and one phase might have negative current while the others are positive, but if I remember some forum posts correctly, the netted values are not correct at all time.

For the three single phase measures, it should not make any difference if you use Triphase or Monophase (except the API response structure I assume).

**Comment by danpoltawski** [comment]
> For the three single phase measures, it should not make any difference if you use Triphase or Monophase (except the API response structure I assume).

We're only interested in the individual measurements, so I think this works for us and I can confirm it works when set to this mode. (Althoguh we are operating in one phase)

**Comment by easimon** [comment]
Do you see any disadvantage or difference apart from the total being counted or not? I guess there must be one, I just don't know what it could be.
